name: coqui
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - pytorch=1.12
# core deps
  - numpy=1.22.4
  - cython=0.29.28
  - scipy>=1.4.0
  - pytorch=1.12
  - torchaudio
  - pysoundfile
  - librosa=0.8.0
  - numba=0.55.2
  - inflect=5.6.0
  - tqdm
  - anyascii
  - pyyaml
  - fsspec>=2021.04.0
  # deps for examples
  - flask
  # deps for inference
  - pysbd
  # deps for notebooks
  # - umap-learn
  - pandas
  # deps for training
  - matplotlib
  # pyworld==0.2.10 # > 0.2.10 is not p3.10.x compatible
  # config management
  - coqpit>=0.0.16
  # chinese g2p deps
  - jieba
  - pypinyin
  # japanese g2p deps
  # mecab-python3==1.0.5
  - unidic-lite==1.0.8
  # gruut+supported langs
  # - gruut[cs,de,es,fr,it,nl,pt,ru,sv]==2.2.3
  - pip:
    # coqui stack
    - trainer
